<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseLocalIdentityHubClient Condition="'$(UseLocalIdentityHubClient)' == ''">false</UseLocalIdentityHubClient>
    <IdentityHubClientPackageVersion Condition="'$(IdentityHubClientPackageVersion)' == ''">1.0.0-dev-6e6d7f</IdentityHubClientPackageVersion>
    <UseLocalIdentityHubContracts Condition="'$(UseLocalIdentityHubContracts)' == ''">false</UseLocalIdentityHubContracts>
    <IdentityHubContractsPackageVersion Condition="'$(IdentityHubContractsPackageVersion)' == ''">1.0.0-dev-6e6d7f</IdentityHubContractsPackageVersion>
  </PropertyGroup>

  <ItemGroup Condition="'$(UseLocalIdentityHubClient)' == 'true'">
    <ProjectReference Include="..\IdentityHub.Client\IdentityHub.Client.csproj" />
  </ItemGroup>

  <ItemGroup Condition="'$(UseLocalIdentityHubClient)' != 'true'">
    <PackageReference Include="IdentityHub.Client" Version="$(IdentityHubClientPackageVersion)" />
  </ItemGroup>

  <ItemGroup Condition="'$(UseLocalIdentityHubContracts)' == 'true'">
    <ProjectReference Include="..\IdentityHub.Contracts\IdentityHub.Contracts.csproj" />
  </ItemGroup>

  <ItemGroup Condition="'$(UseLocalIdentityHubContracts)' != 'true'">
    <PackageReference Include="IdentityHub.Contracts" Version="$(IdentityHubContractsPackageVersion)" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
  </ItemGroup>
</Project>
